package pojos;
// Generated Dec 6, 2018 10:52:41 AM by Hibernate Tools 4.3.1



/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {


     private String idBarang;
     private String nama;
     private int stok;
     private double harga;

    public Barang() {
    }

    public Barang(String idBarang, String nama, int stok, double harga) {
       this.idBarang = idBarang;
       this.nama = nama;
       this.stok = stok;
       this.harga = harga;
    }
   
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public double getHarga() {
        return this.harga;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }




}


