package pojos;
// Generated Dec 6, 2018 10:52:41 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pengiriman generated by hbm2java
 */
public class Pengiriman  implements java.io.Serializable {


     private String idKirim;
     private String idBarang;
     private String namaBarang;
     private int jumlahKirim;
     private String statusTerima;
     private Date tanggalKirim;

    public Pengiriman() {
    }

	
    public Pengiriman(String idKirim, String idBarang, String namaBarang, int jumlahKirim, String statusTerima) {
        this.idKirim = idKirim;
        this.idBarang = idBarang;
        this.namaBarang = namaBarang;
        this.jumlahKirim = jumlahKirim;
        this.statusTerima = statusTerima;
    }
    public Pengiriman(String idKirim, String idBarang, String namaBarang, int jumlahKirim, String statusTerima, Date tanggalKirim) {
       this.idKirim = idKirim;
       this.idBarang = idBarang;
       this.namaBarang = namaBarang;
       this.jumlahKirim = jumlahKirim;
       this.statusTerima = statusTerima;
       this.tanggalKirim = tanggalKirim;
    }
   
    public String getIdKirim() {
        return this.idKirim;
    }
    
    public void setIdKirim(String idKirim) {
        this.idKirim = idKirim;
    }
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahKirim() {
        return this.jumlahKirim;
    }
    
    public void setJumlahKirim(int jumlahKirim) {
        this.jumlahKirim = jumlahKirim;
    }
    public String getStatusTerima() {
        return this.statusTerima;
    }
    
    public void setStatusTerima(String statusTerima) {
        this.statusTerima = statusTerima;
    }
    public Date getTanggalKirim() {
        return this.tanggalKirim;
    }
    
    public void setTanggalKirim(Date tanggalKirim) {
        this.tanggalKirim = tanggalKirim;
    }




}


