package pojos;
// Generated Nov 24, 2018 1:57:22 PM by Hibernate Tools 4.3.1



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private String idSupplier;
     private String nama;
     private String noTelp;
     private String alamat;
     private String username;
     private String password;

    public Supplier() {
    }

    public Supplier(String idSupplier, String nama, String noTelp, String alamat, String username, String password) {
       this.idSupplier = idSupplier;
       this.nama = nama;
       this.noTelp = noTelp;
       this.alamat = alamat;
       this.username = username;
       this.password = password;
    }
   
    public String getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(String idSupplier) {
        this.idSupplier = idSupplier;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


